(function () {
  const gameImages = {
    'PUBG Mobile': 'assets/pubg-photo.jpeg',
    'COD Mobile': 'assets/cod-photo.jpeg',
    Valorant: 'assets/cs2-photo.jpeg',
    Fortnite: 'assets/freefire-photo.jpeg',
    'Apex Legends': 'assets/cod-photo.jpeg',
    'LOL: Wild Rift': 'assets/mobile-legends-photo.jpeg',
  };

  window.wavehubCoaches = [
    {
      id: 'gg',
      name: 'GG',
      game: 'PUBG Mobile',
      service: 'Coaching',
      rank: 'Conqueror',
      tier: 'ace',
      rating: 4.9,
      reviews: 127,
      price: 15,
      tags: ['Experienced', 'Fast Responder'],
      language: 'EN',
      availability: 'now',
      image: gameImages['PUBG Mobile'],
      specialty: 'PUBG Mobile Specialist',
    },
    {
      id: 'acemaster',
      name: 'AceMaster',
      game: 'PUBG Mobile',
      service: 'Rank Push',
      rank: 'Ace Dominator',
      tier: 'ace',
      rating: 4.7,
      reviews: 82,
      price: 14,
      tags: ['100+ Sessions', 'Fast Responder'],
      language: 'EN',
      availability: 'today',
      image: gameImages['PUBG Mobile'],
      specialty: 'Ace Dominator Rank Coach',
    },
    {
      id: 'viperx',
      name: 'ViperX',
      game: 'PUBG Mobile',
      service: 'Coaching',
      rank: 'Conqueror',
      tier: 'ace',
      rating: 4.8,
      reviews: 74,
      price: 17,
      tags: ['Pro Player', 'Fast Responder'],
      language: 'EN',
      availability: 'now',
      image: gameImages['PUBG Mobile'],
      specialty: 'Aggressive Entry Coach',
    },
    {
      id: 'blaze',
      name: 'Blaze',
      game: 'Valorant',
      service: 'Coaching',
      rank: 'Immortal 3',
      tier: 'immortal',
      rating: 4.8,
      reviews: 76,
      price: 18,
      tags: ['Pro Player', 'Fast Responder'],
      language: 'EN',
      availability: 'now',
      image: gameImages.Valorant,
      specialty: 'Valorant Aim Specialist',
    },
    {
      id: 'draco',
      name: 'Draco',
      game: 'COD Mobile',
      service: 'Rank Push',
      rank: 'Legendary',
      tier: 'ace',
      rating: 4.6,
      reviews: 41,
      price: 11,
      tags: ['100+ Sessions', 'Fast Responder'],
      language: 'EN',
      availability: 'weekend',
      image: gameImages['COD Mobile'],
      specialty: 'COD Mobile Ranked Coach',
    },
    {
      id: 'nova-fn',
      name: 'NovaFN',
      game: 'Fortnite',
      service: 'Coaching',
      rank: 'Diamond IV',
      tier: 'diamond',
      rating: 4.7,
      reviews: 54,
      price: 9,
      tags: ['Friendly', 'Fast Responder'],
      language: 'GE',
      availability: 'today',
      image: gameImages.Fortnite,
      specialty: 'Fortnite Build Fight Coach',
    },
    {
      id: 'apexwolf',
      name: 'ApexWolf',
      game: 'Apex Legends',
      service: 'Coaching',
      rank: 'Master',
      tier: 'master',
      rating: 4.6,
      reviews: 38,
      price: 11,
      tags: ['Pro Player', 'Fast Responder'],
      language: 'RU',
      availability: 'today',
      image: gameImages['Apex Legends'],
      specialty: 'Apex Legends Rotation Coach',
    },
    {
      id: 'kingrush',
      name: 'KingRush',
      game: 'PUBG Mobile',
      service: 'Rank Push',
      rank: 'Ace',
      tier: 'ace',
      rating: 4.5,
      reviews: 32,
      price: 8,
      tags: ['Budget Friendly', 'Fast Responder'],
      language: 'EN',
      availability: 'weekend',
      image: gameImages['PUBG Mobile'],
      specialty: 'Budget Rank Push Coach',
    },
    {
      id: 'radiant-ray',
      name: 'RadiantRay',
      game: 'Valorant',
      service: 'Coaching',
      rank: 'Immortal 2',
      tier: 'immortal',
      rating: 4.5,
      reviews: 28,
      price: 16,
      tags: ['Pro Player', '100+ Sessions'],
      language: 'EN',
      availability: 'now',
      image: gameImages.Valorant,
      specialty: 'Valorant Mechanics Coach',
    },
    {
      id: 'codsage',
      name: 'CODSage',
      game: 'COD Mobile',
      service: 'Coaching',
      rank: 'Grandmaster V',
      tier: 'master',
      rating: 4.4,
      reviews: 25,
      price: 9,
      tags: ['Friendly', 'Fast Responder'],
      language: 'GE',
      availability: 'today',
      image: gameImages['COD Mobile'],
      specialty: 'COD Mobile Strategy Coach',
    },
    {
      id: 'riftlord',
      name: 'RiftLord',
      game: 'LOL: Wild Rift',
      service: 'Coaching',
      rank: 'Challenger',
      tier: 'master',
      rating: 4.3,
      reviews: 19,
      price: 12,
      tags: ['Experienced', 'Fast Responder'],
      language: 'EN',
      availability: 'now',
      image: gameImages['LOL: Wild Rift'],
      specialty: 'Wild Rift Macro Coach',
    },
    {
      id: 'stormace',
      name: 'StormAce',
      game: 'PUBG Mobile',
      service: 'Coaching',
      rank: 'Conqueror',
      tier: 'ace',
      rating: 4.6,
      reviews: 41,
      price: 14,
      tags: ['50+ Sessions', 'Fast Responder'],
      language: 'EN',
      availability: 'now',
      image: gameImages['PUBG Mobile'],
      specialty: 'PUBG Mobile Clutch Coach',
    },
  ];
}());
